vm_mem_size="16000"
vm_disk_size="60000"
vm_cpu_num="2"
vm_cpu_cores_num="2"
vm_template_type="medium"
box_name="buster64-medium"
box_tag="dettonville/buster64-medium"
description="Debian Buster[medium]"
