#cloud-config
autoinstall:
  version: 1
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
      - arches: [amd64, i386]
        uri: http://archive.ubuntu.com/ubuntu
      - arches: [default]
        uri: http://ports.ubuntu.com/ubuntu-ports
  early-commands:
    - sudo systemctl stop ssh
    # Block inbound SSH to stop Packer trying to connect during initial install
    - iptables -A INPUT -p tcp --dport 22 -j DROP
    # debugging
    - lsblk -f > /var/log/storage-debug.log
    - cat /autoinstall.yaml > /var/log/autoinstall.yaml 2>&1
    - lsblk -o NAME,SIZE,FSTYPE,LABEL,MOUNTPOINT > /var/log/lsblk-final.log 2>&1

  locale: ${vm_guest_os_language}
  keyboard:
    layout: ${vm_guest_os_keyboard}

  bootloader:
%{ if vm_firmware == "efi-secure" ~}
    type: uefi
%{ else ~}
    type: bios
%{ endif ~}
    install: true

  # Ensure these are indented by exactly 2 spaces
  ${indent(2, storage)}
  ${indent(2, network)}

  identity:
    hostname: ubuntu-server
    username: ${build_username}
    password: ${build_password_encrypted}

  ssh:
    install-server: true
    allow-pw: true
    authorized-keys:
      # replace with the contents of the public key(s) as generated by
      # ssh-keygen or similar tools
      - ${build_ssh_public_key}

  packages:
    - openssh-server
    - open-vm-tools
    - cloud-init
%{ for package in additional_packages ~}
    - ${package}
%{ endfor ~}

  user-data:
    disable_root: false
    package_update: false
    package_upgrade: false
    timezone: ${vm_guest_os_timezone}

  late-commands:
    - |
        cat > /target/etc/ssh/sshd_config.d/99-debug.conf <<EOF
        PermitRootLogin yes
        PasswordAuthentication yes
        PermitEmptyPasswords no
        UsePAM yes
        EOF

    - curtin in-target --target=/target -- systemctl restart ssh

    # Force GRUB installation for BIOS + GPT
    - curtin in-target --target=/target -- grub-install --target=i386-pc /dev/${vm_disk_device}
    - curtin in-target --target=/target -- update-grub

    # Sudoers
    - echo '${build_username} ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/${build_username}
    - curtin in-target --target=/target -- chmod 440 /etc/sudoers.d/${build_username}
