# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "ansible_command" {
  type    = string
  default = "PATH=$PATH:~/.local/bin & PYTHONUNBUFFERED=1 ansible-playbook"
}

variable "ansible_command_orig" {
  type    = string
  default = "ansible-playbook"
}

variable "ansible_command_orig2" {
  type    = string
  default = "PATH=$PATH:~/.local/bin & ANSIBLE_REMOTE_TEMP=/var/tmp/packer-provisioner-ansible-local PYTHONUNBUFFERED=1 ansible-playbook"
}

variable "ansible_galaxy_command" {
  type    = string
  default = "PATH=$PATH:~/.local/bin & ANSIBLE_COLLECTIONS_PATHS=./collections ansible-galaxy"
}

variable "ansible_galaxy_command_orig" {
  type    = string
  default = "ansible-galaxy"
}

variable "ansible_galaxy_command_orig2" {
  type    = string
  default = "ANSIBLE_COLLECTIONS_PATHS=./collections ansible-galaxy"
}

variable "ansible_galaxy_command_orig3" {
  type    = string
  default = "PATH=$PATH:~/.local/bin ansible-galaxy"
}

variable "ansible_galaxy_req_file" {
  type    = string
  default = "../ansible/roles/requirements.packer.yml"
}

variable "ansible_inventory_file" {
  type    = string
  default = "../ansible/inventory/hosts.yml"
}

variable "ansible_inventory_group_vars" {
  type    = string
  default = "../ansible/inventory/group_vars"
}

variable "ansible_playbook_dir" {
  type    = string
  default = "../ansible"
}

variable "ansible_playbook_file" {
  type    = string
  default = "../ansible/bootstrap_vm_template.yml"
}

variable "ansible_staging_directory" {
  type    = string
  default = "/var/tmp/packer-provisioner-ansible-local"
}

variable "ansible_staging_directory_orig" {
  type    = string
  default = "/tmp/packer-provisioner-ansible-local"
}

variable "ansible_vault_password" {
  type    = string
  default = "${env("ANSIBLE_VAULT_PASSWORD")}"
}

variable "boot_command_prefix" {
  type    = string
  default = ""
}

variable "box_tag" {
  type    = string
  default = ""
}

variable "build_type" {
  type    = string
  default = "vsphere-iso"
}

variable "compression_level" {
  type    = string
  default = "6"
}

variable "disk_adapter_type" {
  type    = string
  default = "scsi"
}

variable "esxi_host" {
  type    = string
  default = "esx02.dettonville.int"
}

variable "esxi_password" {
  type    = string
  default = "${env("VMWARE_ESXI_PASSWORD")}"
}

variable "esxi_type" {
  type    = string
  default = "esx5"
}

variable "esxi_username" {
  type    = string
  default = "root"
}

variable "inspec_timeout" {
  type    = string
  default = "50m"
}

variable "ip_settle_timeout" {
  type    = string
  default = "5s"
}

variable "ip_settle_timeout_default" {
  type    = string
  default = "5s"
}

variable "ip_wait_timeout" {
  type    = string
  default = "60m"
}

variable "ip_wait_timeout_default" {
  type    = string
  default = "30m"
}

variable "iso_checksum" {
  type    = string
  default = ""
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_dir" {
  type    = string
  default = ""
}

variable "iso_file" {
  type    = string
  default = ""
}

variable "iso_name" {
  type    = string
  default = "${env("JOB_BASE_NAME")}"
}

variable "iso_url" {
  type    = string
  default = ""
}

variable "qemu_accelerator" {
  type    = string
  default = "kvm"
}

variable "skip_packer_build" {
  type    = string
  default = "false"
}

variable "ssh_handshake_attempts" {
  type    = string
  default = "20"
}

variable "ssh_pass_root" {
  type    = string
  default = "${env("VM_ROOT_PASSWORD")}"
}

variable "ssh_password" {
  type    = string
  default = "${env("PACKER_SSH_PASSWORD")}"
}

variable "ssh_pty" {
  type    = string
  default = "false"
}

variable "ssh_timeout" {
  type    = string
  default = "60m"
}

variable "ssh_user_root" {
  type    = string
  default = "root"
}

variable "ssh_username" {
  type    = string
  default = "packer"
}

variable "vagrant_cloud_token" {
  type    = string
  default = ""
}

variable "vagrant_cloud_username" {
  type    = string
  default = ""
}

variable "vcenter_cluster" {
  type    = string
  default = "Management"
}

variable "vcenter_datacenter" {
  type    = string
  default = "dettonville-dc-01"
}

variable "vcenter_deploy_folder" {
  type    = string
  default = "templates"
}

variable "vcenter_folder" {
  type    = string
  default = "templates"
}

variable "vcenter_host" {
  type    = string
  default = "vcenter7.dettonville.int"
}

variable "vcenter_password" {
  type    = string
  default = "${env("VMWARE_VCENTER_PASSWORD")}"
}

variable "vcenter_username" {
  type    = string
  default = "administrator@vsphere.local"
}

variable "vm_boot_http_directory" {
  type    = string
  default = "http"
}

variable "vm_boot_keygroup_interval" {
  type    = string
  default = "100ms"
}

variable "vm_boot_order" {
  type    = string
  default = "cdrom,disk,ethernet0"
}

variable "vm_boot_order_install" {
  type    = string
  default = "disk,cdrom"
}

variable "vm_boot_wait" {
  type    = string
  default = "5s"
}

variable "vm_build_id" {
  type    = string
  default = "${env("TEMPLATE_BUILD_ID")}"
}

variable "vm_cpu_cores_num" {
  type    = string
  default = "1"
}

variable "vm_cpu_max_num" {
  type    = string
  default = "2"
}

variable "vm_cpu_num" {
  type    = string
  default = "1"
}

variable "vm_data_dir" {
  type    = string
  default = "/data/datacenter/vmware"
}

variable "vm_datastore" {
  type    = string
  default = "nfs_ds1"
}

variable "vm_datastore_orig" {
  type    = string
  default = "esx02_ds1"
}

variable "vm_disk_size" {
  type    = string
  default = "32768"
}

variable "vm_disk_size_large" {
  type    = string
  default = "65536"
}

variable "vm_disk_size_medium" {
  type    = string
  default = "32768"
}

variable "vm_disk_size_small" {
  type    = string
  default = "16240"
}

variable "vm_disk_thin_provisioned" {
  type    = string
  default = "true"
}

variable "vm_disk_type" {
  type    = string
  default = "scsi"
}

variable "vm_disk_type_lsi" {
  type    = string
  default = "lsilogic"
}

variable "vm_disk_type_pvscsi" {
  type    = string
  default = "pvscsi"
}

variable "vm_disk_type_sas" {
  type    = string
  default = "lsilogic-sas"
}

variable "vm_disk_type_scsi" {
  type    = string
  default = "scsi"
}

variable "vm_firmware" {
  type    = string
  default = "bios"
}

variable "vm_guest_os_type" {
  type    = string
  default = "centos7_64Guest"
}

variable "vm_host" {
  type    = string
  default = "esx02.dettonville.int"
}

variable "vm_mem_size" {
  type    = string
  default = "1024"
}

variable "vm_network" {
  type    = string
  default = "VM Network"
}

variable "vm_network_card" {
  type    = string
  default = "vmxnet3"
}

variable "vm_network_card_e1000" {
  type    = string
  default = "e1000"
}

variable "vm_network_mgt" {
  type    = string
  default = "Management Network"
}

variable "vm_network_mgt_orig" {
  type    = string
  default = "VM Network"
}

variable "vm_network_orig" {
  type    = string
  default = "BridgedNetwork"
}

variable "vm_remote_cache_datastore" {
  type    = string
  default = "nfs_ds1"
}

variable "vm_template_datastore" {
  type    = string
  default = "nfs_ds1"
}

variable "vm_template_folder" {
  type    = string
  default = "templates"
}

variable "vm_template_host" {
  type    = string
  default = "esx02.dettonville.int"
}

# All locals variables are generated from variables that uses expressions
# that are not allowed in HCL2 variables.
# Read the documentation for locals blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/locals
locals {
  vm_build_notes = "Build via Packer - date: ${timestamp()} - build tag: ${env("BUILD_TAG")}"
}
